# Generated by Django 4.1.7 on 2023-03-06 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="followed_by",
            field=models.ManyToManyField(
                related_name="followed_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
