# Generated by Django 4.1.7 on 2023-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_copy_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
