# Generated by Django 4.1.7 on 2023-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="devolutions_date",
            field=models.DateField(null=True),
        ),
    ]
