# Generated by Django 4.1.7 on 2023-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
