# Generated by Django 4.1.7 on 2023-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loan_loan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="renovations",
            field=models.IntegerField(null=True),
        ),
    ]
