# Generated by Django 4.1.7 on 2023-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loan_devolutions_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
